# Generated by Django 6.0.1 on 2026-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_code', models.PositiveSmallIntegerField()),
                ('from_number', models.PositiveIntegerField()),
                ('to_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('gar_region', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Phone range',
                'verbose_name_plural': 'Phone ranges',
                'indexes': [models.Index(fields=['def_code', 'from_number', 'to_number'], name='phone_info__def_cod_bbe5ce_idx')],
            },
        ),
    ]
